# Created by Jekyll Writer
title: Jun Wang's blog
author: Jun Wang
description: I'am a code walker.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jstzwj
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: /CodeWalker
